---
abstract: 'Yet Another CPANPLUS Smoke Tester'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPANPLUS-YACSmoke
no_index:
  directory:
    - inc
    - t
requires:
  CPANPLUS: 0.84
  CPANPLUS::Dist::Build: 0.05
  Config::IniFiles: 2.38
  File::Spec: 0
  Module::Build: 0.3
  Module::Load::Conditional: 0
  Regexp::Assemble: 0.34
  SDBM_File: 0
  Sort::Versions: 0
  Test::Reporter: 1.4002
  YAML::Tiny: 0
  perl: 5.6.0
  version: 0.73
resources:
  license: http://dev.perl.org/licenses/
version: 0.27_01
