---
abstract: 'Yet Another CPANPLUS Smoke Tester'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPANPLUS-YACSmoke
no_index:
  directory:
    - inc
    - t
provides:
  CPANPLUS::Config::YACSmoke:
    file: lib/CPANPLUS/Config/YACSmoke.pm
    version: 0.43_03
  CPANPLUS::Dist::YACSmoke:
    file: lib/CPANPLUS/Dist/YACSmoke.pm
    version: 0.43_03
  CPANPLUS::YACSmoke:
    file: lib/CPANPLUS/YACSmoke.pm
    version: 0.43_03
requires:
  CPANPLUS: 0.88
  CPANPLUS::Dist::Build: 0.36
  Config::IniFiles: 2.38
  ExtUtils::CBuilder: 0
  ExtUtils::ParseXS: 0
  File::Spec: 0
  Module::Build: 0.33
  Module::Load::Conditional: 0
  Params::Check: 0
  Regexp::Assemble: 0.34
  SDBM_File: 0
  Sort::Versions: 0
  Test::Reporter: 1.4002
  YAML::Tiny: 0
  perl: 5.6.0
  version: 0.73
resources:
  homepage: http://github.com/bingos/cpanplus-yacsmoke/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/cpanplus-yacsmoke.git
version: 0.43_03
